
networks:
  telemetry-net:
  
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --log.level=debug
    env_file:
      - ./config/.env
    ports:
      - "9090:9090"
    networks:
      - telemetry-net

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    env_file:
      - ./config/.env
    ports:
      - "3100:3100"
    networks:
      - telemetry-net

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: -config.file=/etc/tempo.yaml
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
    env_file:
      - ./config/.env
    ports:
      - "3200:3200"
    networks:
      - telemetry-net

  pyroscope:
    image: grafana/pyroscope:latest
    container_name: pyroscope
    restart: unless-stopped
    ports:
      - "4040:4040"  # Pyroscope UI and API
    environment:
      - PYROSCOPE_LOG_LEVEL=info
      - PYROSCOPE_STORAGE_PATH=/var/lib/pyroscope
      - PYROSCOPE_RETENTION=30d
    volumes:
      - pyroscope-data:/var/lib/pyroscope
    networks:
      - telemetry-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      # - GF_SECURITY_ADMIN_USER=admin
      # - GF_SECURITY_ADMIN_PASSWORD=admin
    env_file:
      - ./config/.env
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
      - tempo
      - pyroscope
    networks:
      - telemetry-net
    volumes:
      - ./data/grafana:/var/lib/grafana

  agent:
    image: grafana/agent:latest
    container_name: agent
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    entrypoint: ["/bin/sh", "-c", "grafana-agent --config.file=/etc/agent-config.yaml 2>&1 | tee /var/log/grafana-agent.log"]
    volumes:
      - ./config/agent-config.yaml:/etc/agent-config.yaml
      - ./log:/var/host-log
    env_file:
      - ./config/.env
    ports:
      - "12345:12345"
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - prometheus
      - loki
      - tempo
    networks:
      - telemetry-net

volumes:
  grafana-data:
  prometheus-data:
  loki-data:
  tempo-data:
  pyroscope-data: